### ISSUE TITLE
Add License to Repo

### ISSUE THREAD

**Issue by suneettipirneni** [cs-discord-at-ucf/lion#506]
Add an open source license to the repo, this would clear up any ambiguities on how the code in this repo can be used/forked/distributed. My recommendation is the MIT license. This should probably be done sooner than later.

This will also most likely involve @tanndlin, @joey-colon and @c650's input.

**Comment by rob-3** [comment]
Just FYI, you will need to get all parties who have ever contributed code that is still present in the codebase to agree to whatever license you choose.

**Comment by suneettipirneni** [comment]
So according to the package.json the license it ISC which is just simplified version of MIT. But it's not clear if this is intentional or not.

**Comment by rob-3** [comment]
> So according to the package.json the license is ISC which is just simplified version of MIT. But it's not clear if this is intentional or not.

I don't think we can really say that "ISC" being in `package.json` proves anyone consented to use the ISC license, especially since that is a file many people probably don't read and there is no `LICENSE.md` file or mention in the `README.md` or anywhere else I can see.

To fix this, we need the following people to comment here saying they agree to license their existing contributions under the MIT license:

- [ ] @tanndlin 
- [ ] @c650 
- [ ] @joey-colon 
- [ ] @CallumCoy 
- [ ] @suneettipirneni 
- [ ] @gooca 
- [ ] @VijayStroup 
- [ ] @TylerMathis 
- [ ] @PromAtlas 
- [ ] @Armintron 
- [ ] @brettfazio 
- [ ] @Helithumper 
- [ ] @Kurtoid 
- [ ] @SageJacob 
- [ ] @zenith110 
- [ ] @MattNot 
- [ ] @LemensRUs 
- [ ] @ElbertTse

**Comment by rob-3** [comment]
A couple of these people have 1 liners that we could argue aren't copyrightable if they are hard to track down, but most have a significant contribution.

**Comment by Helithumper** [comment]
AFAIK if you add a license to a piece of code it only effects the code changes made _after_ the change, if that makes sense. At least that's how I understood the change when it came to Elastic changing their license. Either way LGTM

**Comment by rob-3** [comment]
> AFAIK if you add a license to a piece of code it only effects the code changes made _after_ the change, if that makes sense. At least that's how I understood the change when it came to Elastic changing their license. Either way LGTM

Correct, which is why we can't add MIT today and be done with it. Notice the above language:

> we need the following people to comment here saying they agree to license their *existing contributions* under the MIT license:

This clears up the legal status of the old code, after which we can slap on MIT and have a fully legal MIT licensed codebase.

**Comment by c650** [comment]
> > So according to the package.json the license is ISC which is just simplified version of MIT. But it's not clear if this is intentional or not.
> 
> I don't think we can really say that "ISC" being in `package.json` proves anyone consented to use the ISC license, especially since that is a file many people probably don't read and there is no `LICENSE.md` file or mention in the `README.md` or anywhere else I can see.
> 
> To fix this, we need the following people to comment here saying they agree to license their existing contributions under the MIT license:
> 
> * [x]  @tanndlin
> * [ ]  @c650
> * [ ]  @joey-colon
> * [ ]  @CallumCoy
> * [x]  @suneettipirneni
> * [ ]  @gooca
> * [ ]  @VijayStroup
> * [x]  @TylerMathis
> * [ ]  @PromAtlas
> * [x]  @Armintron
> * [ ]  @brettfazio
> * [ ]  @Helithumper
> * [ ]  @Kurtoid
> * [ ]  @SageJacob
> * [ ]  @zenith110
> * [ ]  @MattNot
> * [ ]  @LemensRUs
> * [ ]  @ElbertTse

I agree that all my contributions to this project can be licensed under MIT License

**Comment by Armintron** [comment]
I agree that all my contributions to this project can be licensed under MIT License

**Comment by PromAtlas** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by ElbertTse** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by zenith110** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by TylerMathis** [comment]
I agree that all my contributions to this project can be licensed under MIT License. 🤪

**Comment by brettfazio** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by Clev7** [comment]
I agree that all my contributions to this project can be licensed under MIT License

**Comment by VijayStroup** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by CallumCoy** [comment]
I agree that all my contributions to this project can be licensed under MIT License. Also hi.

**Comment by gooca** [comment]
just add the license 4head u don't have to invent bureaucracy and ping every1 who did 1 liners lol

**Comment by rob-3** [comment]
> just add the license 4head u don't have to invent bureaucracy and ping every1 who did 1 liners b4 u can use it lol

Sorry if you just had a one-liner; I am just going off of the git history and the listed contributors and including everyone for completeness. I want to be explicit about consent and make sure I'm respecting everyone's rights to their own code.

If you could affirm your consent with the message everyone has been using above, that would be great!

**Comment by rob-3** [comment]
Thanks all who have taken the time to agree here. Sadly, this issue is indefinitely blocked by Joey's failure to agree. **Please don't go message him or otherwise harass anyone**; it is his code and his right to license (or not license) it as it sees fit. We agreed to disagree.

Unfortunately, this development means I will not be contributing to Lion. There are a number of issues associated with unlicensed projects; I won't go into detail here, but [this GitHub provided website](https://choosealicense.com/no-permission/) does a good job explaining them simply. In short, doing basically anything with this code is likely copyright infringement. In practical terms, this likely means that, down the line, a single vindictive contributor could send a copyright takedown and potentially be completely legally in the right.

If you're interested in another discord bot project that will be licensed, Knight Hacks (the hackathon and software development RSO) will be starting up development on our own bot, Lancelot, shortly. You can find our discord in the #clubs channel of the CS discord!

Feel free to reach out to me with any questions or concerns!

Rob (@rob-3 on discord and github)

**Comment by joeydotdev** [comment]
I agree that all my contributions to this project can be licensed under MIT License

**Comment by TheIceCreamBear** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by rob-3** [comment]
Updated with new people

**Comment by CommanderRoot** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by LambdaPaul** [comment]
(For completeness)
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by rob-3** [comment]
AFAIK, the only people we still need to get this done are

- [ ] @gooca 
- [ ] @serspencer 
- [ ] @Zachmayers 
- [ ] @GarrettParlier 
- [ ] @bquach2 

If the above 5 people agree to license their contributions under the MIT license following the template of those above, we can license the entire repository under MIT and be done with this for once and for all.

**Comment by bquach2** [comment]
I agree that all my contributions can be licensed under MIT license

**Comment by serspencer** [comment]
I agree to have all of my contributions licensed under MIT license.

Thanks,
Spencer

On May 14, 2022, at 3:13 PM, Brandon Quach ***@***.***> wrote:

﻿

I agree that all my contributions can be licensed under MIT license

**Comment by Zachmayers** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by landoniwnl** [comment]
I agree that all my contributions to this project can be licensed under MIT License.

**Comment by GarrettParlier** [comment]
I agree that all my contributions to this project can be licensed under MIT License.
