### ISSUE TITLE
!FE command with information and FAQ about the FE

### ISSUE THREAD

**Issue by noahwhite07** [cs-discord-at-ucf/lion#693]

**Comment by tanndlin** [comment]
Very similar to #656 and #128

Just a command that would regurgitate some sort of mostly static text.
Do you have any ideas on how to implement this. I haven't really gotten to these issues because they are all the same principle (maybe even make them all 1 command). Hard coding the response isn't really a good idea tho, so open to suggestions

**Comment by c650** [comment]
better off just having some community members writing a wiki (could be here or another repo under cs-discord-at-ucf or *wherever*) and then setting channel topic to point to that url
